### ISSUE TITLE
approved unapproved titles

### ISSUE THREAD

**Issue by Tsuchimikado** [Hiyori-API/checker_mal#15]
found 102 approved titles that are still listed in https://sean.fish/mal_unapproved/manga page
some of them was approved month ago

<details>
<summary>Click to expand</summary>

101732 (Novel) - Pheromone Tantei Yappari Junan no Hibi https://myanimelist.net/manga/101732/pheromone-tantei-series
101854 (Novel) - Skip Beat! Kyouko no Zenryoku Full Course! https://myanimelist.net/manga/101854/shousetsu-skip-beat-kyouko-no-zenryoku-full-course
102254 (Manga) - Kujaku Ou Denki https://myanimelist.net/manga/102254/kujakuou-denki
102255 (Manga) - Kai no tora Takeda Shingen https://myanimelist.net/manga/102255/kai-no-tora-takeda-shingen
106764 (Manga) - Kinnikuman One Shot Collection 2011 - 2014 https://myanimelist.net/manga/106764/kinnikuman-yomikiri-kessakusen-2011-2014
106795 (Manga) - High School Agent https://myanimelist.net/manga/106795/high-school-agent
106840 (Novel) - Mofumofu Hoikuen to Harapeko Ookami https://myanimelist.net/manga/106840/mofumofu-hoikuen-to-harapeko-ookami
106930 (Manga) - Yummy Yummy Boy - Yen Man No Hiketsu https://myanimelist.net/manga/106930/yummy-yummy-boy-yen-man-no-hiketsu
107033 (Manga) - Ore no Sora https://myanimelist.net/manga/107033/ore-no-sora
107451 (Novel) - Tsuki no Sabaku no Ryakudatsu Hanayome https://myanimelist.net/manga/107451/tsuki-no-sabaku-no-ryakudatsu-hanayome
107511 (Manga) - Boku to Furio to Koutei de https://myanimelist.net/manga/107511/boku-to-furio-to-koutei-de
107528 (Manga) - Space https://myanimelist.net/manga/107528/hokenshitsu-made-nan-m-dj-space
107692 (Manga) - Haou Kessen Lion https://myanimelist.net/manga/107692/haou-kessen-lion
107693 (Manga) - BW - Majan Hoshitori Densetsu https://myanimelist.net/manga/107693/bw-mahjong-hoshitori-densetsu
107742 (Manga) - Kanashimi no Machi https://myanimelist.net/manga/107742/kanashimi-no-machi
107773 (Doujinshi) - Kare to Kare no Ijiwaru na Kyori dj - Zero Kyori https://myanimelist.net/manga/107773/kare-to-kare-no-ijiwaru-na-kyori-dj-zero-kyori
107803 (Manga) - Sunao ni Juujun ni Shitsukete https://myanimelist.net/manga/107803/sunao-ni-juujun-ni-shitsukete
107806 (Manga) - Grancrest Senki - Dropout https://myanimelist.net/manga/107806/grancrest-senki-dropout
107807 (Manga) - Otogizoushi https://myanimelist.net/manga/107807/otogizoushi
107879 (Manga) - Ze: Haru no Yuki https://myanimelist.net/manga/107879/ze-haru-no-yuki
107889 (Manga) - Starmyu Stardust’s Dream https://myanimelist.net/manga/107889/starmyu-stardust-s-dream
107892 (Manga) - Miyatake Miracle https://myanimelist.net/manga/107892/miyatake-miracle
108149 (Manga) [NSFW] - Nama de Naka o Ippai ni Shite. https://myanimelist.net/manga/108149/nama-de-naka-wo-ippai-ni-shite
109010 (Manga) - Piri Fuwa Tsu-n https://myanimelist.net/manga/109010/piri-fuwa-tsuun
109043 (Manga) - Kimama ni Idol https://myanimelist.net/manga/109043/kimama-ni-idol
109162 (Manga) - Violent Runner Vibrator https://myanimelist.net/manga/109162/bakusou-ningen-vibrator
109167 (Manga) - Girl@Girl https://myanimelist.net/manga/109167/girl-girl
109200 (One-shot) - SSG CODE:0 https://myanimelist.net/manga/109200/ssg-code-0
109223 (Manga) - Manga de Wakaru - Hontou wa Ecchi na Butsurigaku https://myanimelist.net/manga/109223/manga-de-wakaru-hontou-wa-ecchi-na-butsurigaku
109302 (Manga) - Senjou Manga Series https://myanimelist.net/manga/109302/senjou-manga-series
109368 (Manga) - D4 Princess https://myanimelist.net/manga/109368/d4-princess
109411 (Manga) - Wakakusa Monogatari https://myanimelist.net/manga/109411/wakakusa-monogatari
109424 (One-shot) - Seaside Return https://myanimelist.net/manga/109424/seaside-return
109507 (Manga) - Toragurumi Araburu! https://myanimelist.net/manga/109507/toragurumi-araburu
109508 (Manga) - Sono Egao Suki Janai https://myanimelist.net/manga/109508/sono-egao-suki-ja-nai
109524 (Manga) - Yunomi Mix https://myanimelist.net/manga/109524/yunomi-mix
109567 (Manga) - Kamo no Mizukaki https://myanimelist.net/manga/109567/kamo-no-mizukaki
109579 (One-shot) - Bishounen https://myanimelist.net/manga/109579/bishounen
109660 (Manga) - Träumerei https://myanimelist.net/manga/109660/traumerei
109661 (Manga) - Yajikita in Deep https://myanimelist.net/manga/109661/yajikita-in-deep
109685 (Manga) - Azuma-san to Itakura-san wa Koi wo Suru. https://myanimelist.net/manga/109685/azuma-san-to-itakura-senpai-wa-koi-wo-suru
109692 (Manga) - Gorin no Sho https://myanimelist.net/manga/109692/chouyaku-gorin-no-sho
109705 (Manga) - tomodachi wo kudaku houhou https://myanimelist.net/manga/109705/tomodachi-wo-kudoku-houhou
109706 (Manga) - koibito wo kudaku houhou https://myanimelist.net/manga/109706/koibito-wo-kudoku-houhou
117077 (Novel) - Kimi no Suizou wo Tabetai https://myanimelist.net/manga/117077/kimi-no-suizou-wo-tabetai
119771 (One-shot) [NSFW] - Muchi homo shin'yū (kanojo) https://myanimelist.net/manga/119771/muchi-homo-kanojo
119949 (Novel) - Ankoku Joshi https://myanimelist.net/manga/119949/ankoku-joshi
120044 (Manga) - Sekitou Elergy - Toukyou Monogatari https://myanimelist.net/manga/120044/sekitou-elegy-tokyo-monogatari
120232 (Manga) - Lady Rin! https://myanimelist.net/manga/120232/lady-rin
120297 (One-shot) - Sentimental Beach Side https://myanimelist.net/manga/120297/sentimental-beach-side
120393 (One-shot) - Elfen Lied Tokubetsu-hen https://myanimelist.net/manga/120393/elfen-lied-tokubetsu-hen
120569 (Manga) - K-On! Story Anthology Comic https://myanimelist.net/manga/120569/k-on-story-anthology-comic
120616 (Novel) - Urasekai Picnic https://myanimelist.net/manga/120616/urasekai-picnic
120847 (Manga) [NSFW] - Mama Koubi https://myanimelist.net/manga/120847/mama-koubi
120923 (Manga) - 美脚ミミック、ハルミさん ~転生モンスター異世界成り上がり伝説~ https://myanimelist.net/manga/120923/bikyaku-mimic-harumi-san-tensei-monster-isekai-nariagari-densetsu
120961 (Novel) - Konyakuhaki Kara Hajimeru Akuyaku Reijou no Kangoku Slow Life https://myanimelist.net/manga/120961/konyaku-haki-kara-hajimaru-akuyaku-reijou-no-kangoku-slow-life
120975 (Manga) [NSFW] - Uchi ni wa Yuurei-san ga Imasu https://myanimelist.net/manga/120975/uchi-ni-wa-yuurei-san-ga-imasu
121046 (Manga) - Color Recipe Clear https://myanimelist.net/manga/121046/color-recipe-clear
121068 (Manga) [NSFW] - Tsumatorare https://myanimelist.net/manga/121068/tsumatorare
121152 (Manga) - Stigmata: Aikon https://myanimelist.net/manga/121152/stigmata-aikon
121263 (Novel) - Haikei, akumana kishi-sama no hanayome ni narimashite https://myanimelist.net/manga/121263/haikei-akuma-na-kishi-sama-no-hanayome-ni-narimashite-amaama-shinkon-fuufu-mezashite-ganbarimasu
121339 (Novel) - Futsugyou https://myanimelist.net/manga/121339/futsugyou
122211 (Manga) - Kimi no Sekai ni Ite Itai https://myanimelist.net/manga/122211/kimi-no-sekai-ni-iteitai
122531 (Novel) - Kimi wa Tsukiyo ni Hikari Kagayaku https://myanimelist.net/manga/122531/kimi-wa-tsukiyo-ni-hikarikagayaku
122877 (Novel) - Teogonia https://myanimelist.net/manga/122877/teogonia
123180 (Manga) - Yamikin toritate no osoroshi jittai https://myanimelist.net/manga/123180/kakusanteki-emotion
123225 (Manga) - Kimi ni Soba ni Itehoshii https://myanimelist.net/manga/123225/kimi-ni-soba-ni-itehoshii
123356 (Manga) - Komatta Jiisan https://myanimelist.net/manga/123356/komatta-jiisan
123364 (Manga) - A Boy. A Girl. https://myanimelist.net/manga/123364/a-boy-a-girl
123564 (Manga) - Seija no Koushin Revenge https://myanimelist.net/manga/123564/seija-no-koushin-revenge
123924 (Manga) - Kyonyuu Tights https://myanimelist.net/manga/123924/kyonyuu-tights-kuro-tights-bishoujo-to-icha-ero-shichau-anthology-comic
123930 (Manga) - Black Girls Talk https://myanimelist.net/manga/123930/black-girl-s-talk
123935 (Manga) - Chocolate: Shakaijin Yuri Anthology https://myanimelist.net/manga/123935/chocolat-shakaijin-yuri-anthology
124150 (Manga) - Kesaran Nanigashi to Soup'ya-san https://myanimelist.net/manga/124150/kesaran-nanigashi-to-soupya-san
124247 (Manga) - Wareware wa Uchuujin da!! https://myanimelist.net/manga/124247/wareware-wa-uchuujin-da
124440 (Manga) - Kimi ga Suki de Komaru https://myanimelist.net/manga/124440/kimi-ga-suki-de-komaru
125842 (Novel) - Koi suru Kiseichû https://myanimelist.net/manga/125842/koisuru-kiseichuu
126479 (Novel) - Mikkakan no Koufuku https://myanimelist.net/manga/126479/mikkakan-no-koufuku
128560 (One-shot) [NSFW] - Maji Good Chance Doutei https://myanimelist.net/manga/128560/maji-good-chance-doutei
128561 (One-shot) [NSFW] - Chifuyu-chan wa Damasareyasui! https://myanimelist.net/manga/128561/chifuyu-chan-wa-damasareyasui
128564 (Manga) [NSFW] - Love Splash https://myanimelist.net/manga/128564/love-splash
128565 (One-shot) [NSFW] - Yoku Ataru Uranaishi https://myanimelist.net/manga/128565/yoku-ataru-uranaishi
128593 (Doujinshi) - Me ga Sametara Onna no Ko ni natte ita Hanashi https://myanimelist.net/manga/128593/mememori-kun-ni-wa-kanawanai
128612 (Manga) [NSFW] - Hagane no Koromo no Otome-tachi https://myanimelist.net/manga/128612/hagane-no-koromo-no-otome-tachi
128907 (Manga) - Maou no Hajimekata Gaiden Mary-chan no Osunaba Dungeon https://myanimelist.net/manga/128907/maou-no-hajimekata-gaiden-mary-chan-no-osunaba-dungeon
128980 (Manga) - Douse Horu Nara Fukai Ana. https://myanimelist.net/manga/128980/douse-horu-nara-fukai-ana
129314 (One-shot) - Akujiki no Dinner https://myanimelist.net/manga/129314/akujiki-no-dinner
129520 (Manga) [NSFW] - Koizome Marking https://myanimelist.net/manga/129520/koizome-marking
131805 (Manga) [NSFW] - Dosukebe Oneichan https://myanimelist.net/manga/131805/dosukebe-onei-chan
131935 (Doujinshi) [NSFW] - Kanojo no Ane wa Gal de Bitch de Yariman de https://myanimelist.net/manga/131935/kanojo-no-ane-wa-gal-de-bitch-de-yariman-de
131936 (Doujinshi) [NSFW] - Papakatsu Gal to Kimeseku kara no Ranpako https://myanimelist.net/manga/131936/papakatsu-gal-to-kimeseku-kara-no-ranpako
131938 (Doujinshi) [NSFW] - Inma Kyuusei https://myanimelist.net/manga/131938/inma-kyuusei
131942 (Doujinshi) [NSFW] - Hidai! Kakuchou! Nikubenki Kaizou Shinryou https://myanimelist.net/manga/131942/hidai-kakuchou-nikubenki-kaizou-shinryou
133709 (Light Novel) - Harapeko na Joushi no I wo Tsukamu Houhou: Sasen-saki wa Kyuutei Majutsushi no Senzoku Chef https://myanimelist.net/manga/133709/harapeko-na-joushi-no-i-wo-tsukamu-houhou-sasen-saki-wa-kyuutei-majutsushi-no-senzoku-chef
133726 (Light Novel) - Erotical Wizard to 12 Nin no Hanayome https://myanimelist.net/manga/133726/erotical-wizard-to-12-nin-no-hanayome
133800 (Manga) - Kedamonotachi No Jikan https://myanimelist.net/manga/133800/kedamono-tachi-no-jikan-kyouizon-shoukougun
133894 (Manga) - Hitorimi Desuga Nanika? https://myanimelist.net/manga/133894/hitorimi-desu-ga-nani-ka
134878 (Manga) - Trigger Keeper https://myanimelist.net/manga/134878/trigger-keeper
136228 (Manga) - Ikki Yakou https://myanimelist.net/manga/136228/ikki-yakou
136840 (Manga) - Nippen! https://myanimelist.net/manga/136840/nippen
137368 (Manga) - DAYS ~fragment~ https://myanimelist.net/manga/137368/days-fragment
137759 (Manga) - Himitsu Sentai Gorenger https://myanimelist.net/manga/137759/himitsu-sentai-gorenger

</details>

**Comment by purarue** [comment]
Hey, thanks for letting me know

will try and look at it later tonight

**Comment by purarue** [comment]
Still see things being added to the cache in general, so I don't think its a major problem -- its probably just not requesting pages far enough back to see that those entries have been approved

I tweaked the numbers a bit and will monitor it to see if that fixed it, else continue debugging

Will update here in a bit

**Comment by purarue** [comment]
Yeah, seems that because of #16, this wasn't checking pages far enough back commonly enough, so it just checking those pages less often

[I've bumped the numbers](https://github.com/Hiyori-API/checker_mal/commit/44ef3340a5e3f726a27d74acb554be755e0752e8) so that should happen less frequently -- these isn't really a sure way to do this since I don't want to be constantly hitting every page on MAL to figure out what hasn't been approved

Most of the changes are listed [here](https://github.com/seanbreckenridge/mal-id-cache/commit/b47f52a9176eef5af39d712ac9e18ac89998f048#diff-5e1ecee06a7fc06f305ae5c12acfe7a7f67b8ece7af76932ed3afab00c3c6921)

Let me know if you still see anything wrong

Thanks again

**Comment by Tsuchimikado** [comment]
two more

108928 (Manga) - Juumin yo Koigokoro wo Idake
https://myanimelist.net/manga/108928/Juumin_yo_Koigokoro_wo_Idake/stats?m=all&show=75

111348 (Manga) - Iwakutsuki! Miyako-sou
https://myanimelist.net/manga/111348/Iwakutsuki_Miyako-sou/stats?m=all#members

**Comment by purarue** [comment]
Yeah, like previously

Since those IDs are so far back, it hasn't found those yet

It searches back that far once a month, so it'll find them eventually

I'll think about adding some mechanism for a user to request an ID to be checked by the member count, since it's not really feasible to search the entire database constantly

**Comment by purarue** [comment]
added an API so I can search back https://github.com/Hiyori-API/checker_mal/commit/ff9240f19ad747f3f11b20d36cd62a82da88b7a9, just triggered it to search back 100 pages for manga, so it should find those in a bit

If you have a discord/want to discuss some sort of way to trigger this, feel free to [join the server here](https://github.com/seanbreckenridge/mal-notify-bot#join) -- is the main way I'd trigger it since I don't want to make the API public for fear of my server getting spammed/blocked
